# Copyright 2015 The BoringSSL Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is created by generate_build_files.py. Do not edit manually.
# To specify a custom path prefix, set BORINGSSL_ROOT before including this
# file, or use list(TRANSFORM ... PREPEND) from CMake 3.12.

set(crypto_sources
  ${BORINGSSL_ROOT}src/crypto/aes/aes.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_bitstr.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_bool.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_d2i_fp.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_dup.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_gentm.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_i2d_fp.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_int.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_mbstr.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_object.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_octet.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_strex.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_strnid.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_time.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_type.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/a_utctm.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/asn1_lib.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/asn1_par.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/asn_pack.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/f_int.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/f_string.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/posix_time.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/tasn_dec.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/tasn_enc.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/tasn_fre.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/tasn_new.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/tasn_typ.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/tasn_utl.cc
  ${BORINGSSL_ROOT}src/crypto/base64/base64.cc
  ${BORINGSSL_ROOT}src/crypto/bio/bio.cc
  ${BORINGSSL_ROOT}src/crypto/bio/bio_mem.cc
  ${BORINGSSL_ROOT}src/crypto/bio/connect.cc
  ${BORINGSSL_ROOT}src/crypto/bio/errno.cc
  ${BORINGSSL_ROOT}src/crypto/bio/fd.cc
  ${BORINGSSL_ROOT}src/crypto/bio/file.cc
  ${BORINGSSL_ROOT}src/crypto/bio/hexdump.cc
  ${BORINGSSL_ROOT}src/crypto/bio/pair.cc
  ${BORINGSSL_ROOT}src/crypto/bio/printf.cc
  ${BORINGSSL_ROOT}src/crypto/bio/socket.cc
  ${BORINGSSL_ROOT}src/crypto/bio/socket_helper.cc
  ${BORINGSSL_ROOT}src/crypto/blake2/blake2.cc
  ${BORINGSSL_ROOT}src/crypto/bn/bn_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/bn/convert.cc
  ${BORINGSSL_ROOT}src/crypto/bn/div.cc
  ${BORINGSSL_ROOT}src/crypto/bn/exponentiation.cc
  ${BORINGSSL_ROOT}src/crypto/bn/sqrt.cc
  ${BORINGSSL_ROOT}src/crypto/buf/buf.cc
  ${BORINGSSL_ROOT}src/crypto/bytestring/asn1_compat.cc
  ${BORINGSSL_ROOT}src/crypto/bytestring/ber.cc
  ${BORINGSSL_ROOT}src/crypto/bytestring/cbb.cc
  ${BORINGSSL_ROOT}src/crypto/bytestring/cbs.cc
  ${BORINGSSL_ROOT}src/crypto/bytestring/unicode.cc
  ${BORINGSSL_ROOT}src/crypto/chacha/chacha.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/derive_key.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/e_aesctrhmac.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/e_aeseax.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/e_aesgcmsiv.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/e_chacha20poly1305.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/e_des.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/e_null.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/e_rc2.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/e_rc4.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/e_tls.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/get_cipher.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/tls_cbc.cc
  ${BORINGSSL_ROOT}src/crypto/cms/cms.cc
  ${BORINGSSL_ROOT}src/crypto/conf/conf.cc
  ${BORINGSSL_ROOT}src/crypto/cpu_aarch64_apple.cc
  ${BORINGSSL_ROOT}src/crypto/cpu_aarch64_fuchsia.cc
  ${BORINGSSL_ROOT}src/crypto/cpu_aarch64_linux.cc
  ${BORINGSSL_ROOT}src/crypto/cpu_aarch64_openbsd.cc
  ${BORINGSSL_ROOT}src/crypto/cpu_aarch64_sysreg.cc
  ${BORINGSSL_ROOT}src/crypto/cpu_aarch64_win.cc
  ${BORINGSSL_ROOT}src/crypto/cpu_arm_freebsd.cc
  ${BORINGSSL_ROOT}src/crypto/cpu_arm_linux.cc
  ${BORINGSSL_ROOT}src/crypto/cpu_intel.cc
  ${BORINGSSL_ROOT}src/crypto/crypto.cc
  ${BORINGSSL_ROOT}src/crypto/curve25519/curve25519.cc
  ${BORINGSSL_ROOT}src/crypto/curve25519/curve25519_64_adx.cc
  ${BORINGSSL_ROOT}src/crypto/curve25519/spake25519.cc
  ${BORINGSSL_ROOT}src/crypto/des/des.cc
  ${BORINGSSL_ROOT}src/crypto/dh/dh_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/dh/params.cc
  ${BORINGSSL_ROOT}src/crypto/digest/digest_extra.cc
  ${BORINGSSL_ROOT}src/crypto/dsa/dsa.cc
  ${BORINGSSL_ROOT}src/crypto/dsa/dsa_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/ec/ec_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/ec/ec_derive.cc
  ${BORINGSSL_ROOT}src/crypto/ec/hash_to_curve.cc
  ${BORINGSSL_ROOT}src/crypto/ecdh/ecdh.cc
  ${BORINGSSL_ROOT}src/crypto/ecdsa/ecdsa_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/ecdsa/ecdsa_p1363.cc
  ${BORINGSSL_ROOT}src/crypto/engine/engine.cc
  ${BORINGSSL_ROOT}src/crypto/err/err.cc
  ${BORINGSSL_ROOT}src/crypto/evp/evp.cc
  ${BORINGSSL_ROOT}src/crypto/evp/evp_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/evp/evp_ctx.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_dh.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_dh_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_dsa_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_ec.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_ec_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_ed25519.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_ed25519_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_hkdf.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_rsa.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_rsa_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_x25519.cc
  ${BORINGSSL_ROOT}src/crypto/evp/p_x25519_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/evp/pbkdf.cc
  ${BORINGSSL_ROOT}src/crypto/evp/print.cc
  ${BORINGSSL_ROOT}src/crypto/evp/scrypt.cc
  ${BORINGSSL_ROOT}src/crypto/evp/sign.cc
  ${BORINGSSL_ROOT}src/crypto/ex_data.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bcm.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/fips_shared_support.cc
  ${BORINGSSL_ROOT}src/crypto/fuzzer_mode.cc
  ${BORINGSSL_ROOT}src/crypto/hpke/hpke.cc
  ${BORINGSSL_ROOT}src/crypto/hrss/hrss.cc
  ${BORINGSSL_ROOT}src/crypto/kyber/kyber.cc
  ${BORINGSSL_ROOT}src/crypto/lhash/lhash.cc
  ${BORINGSSL_ROOT}src/crypto/md4/md4.cc
  ${BORINGSSL_ROOT}src/crypto/md5/md5.cc
  ${BORINGSSL_ROOT}src/crypto/mem.cc
  ${BORINGSSL_ROOT}src/crypto/mldsa/mldsa.cc
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem.cc
  ${BORINGSSL_ROOT}src/crypto/obj/obj.cc
  ${BORINGSSL_ROOT}src/crypto/obj/obj_xref.cc
  ${BORINGSSL_ROOT}src/crypto/pem/pem_all.cc
  ${BORINGSSL_ROOT}src/crypto/pem/pem_info.cc
  ${BORINGSSL_ROOT}src/crypto/pem/pem_lib.cc
  ${BORINGSSL_ROOT}src/crypto/pem/pem_oth.cc
  ${BORINGSSL_ROOT}src/crypto/pem/pem_pk8.cc
  ${BORINGSSL_ROOT}src/crypto/pem/pem_pkey.cc
  ${BORINGSSL_ROOT}src/crypto/pem/pem_x509.cc
  ${BORINGSSL_ROOT}src/crypto/pem/pem_xaux.cc
  ${BORINGSSL_ROOT}src/crypto/pkcs7/pkcs7.cc
  ${BORINGSSL_ROOT}src/crypto/pkcs7/pkcs7_x509.cc
  ${BORINGSSL_ROOT}src/crypto/pkcs8/p5_pbev2.cc
  ${BORINGSSL_ROOT}src/crypto/pkcs8/pkcs8.cc
  ${BORINGSSL_ROOT}src/crypto/pkcs8/pkcs8_x509.cc
  ${BORINGSSL_ROOT}src/crypto/poly1305/poly1305.cc
  ${BORINGSSL_ROOT}src/crypto/poly1305/poly1305_arm.cc
  ${BORINGSSL_ROOT}src/crypto/poly1305/poly1305_vec.cc
  ${BORINGSSL_ROOT}src/crypto/pool/pool.cc
  ${BORINGSSL_ROOT}src/crypto/rand/deterministic.cc
  ${BORINGSSL_ROOT}src/crypto/rand/fork_detect.cc
  ${BORINGSSL_ROOT}src/crypto/rand/forkunsafe.cc
  ${BORINGSSL_ROOT}src/crypto/rand/getentropy.cc
  ${BORINGSSL_ROOT}src/crypto/rand/ios.cc
  ${BORINGSSL_ROOT}src/crypto/rand/passive.cc
  ${BORINGSSL_ROOT}src/crypto/rand/rand.cc
  ${BORINGSSL_ROOT}src/crypto/rand/trusty.cc
  ${BORINGSSL_ROOT}src/crypto/rand/urandom.cc
  ${BORINGSSL_ROOT}src/crypto/rand/windows.cc
  ${BORINGSSL_ROOT}src/crypto/rc4/rc4.cc
  ${BORINGSSL_ROOT}src/crypto/refcount.cc
  ${BORINGSSL_ROOT}src/crypto/rsa/rsa_asn1.cc
  ${BORINGSSL_ROOT}src/crypto/rsa/rsa_crypt.cc
  ${BORINGSSL_ROOT}src/crypto/rsa/rsa_extra.cc
  ${BORINGSSL_ROOT}src/crypto/rsa/rsa_print.cc
  ${BORINGSSL_ROOT}src/crypto/sha/sha1.cc
  ${BORINGSSL_ROOT}src/crypto/sha/sha256.cc
  ${BORINGSSL_ROOT}src/crypto/sha/sha512.cc
  ${BORINGSSL_ROOT}src/crypto/siphash/siphash.cc
  ${BORINGSSL_ROOT}src/crypto/slhdsa/slhdsa.cc
  ${BORINGSSL_ROOT}src/crypto/spake2plus/spake2plus.cc
  ${BORINGSSL_ROOT}src/crypto/stack/stack.cc
  ${BORINGSSL_ROOT}src/crypto/thread.cc
  ${BORINGSSL_ROOT}src/crypto/thread_none.cc
  ${BORINGSSL_ROOT}src/crypto/thread_pthread.cc
  ${BORINGSSL_ROOT}src/crypto/thread_win.cc
  ${BORINGSSL_ROOT}src/crypto/trust_token/pmbtoken.cc
  ${BORINGSSL_ROOT}src/crypto/trust_token/trust_token.cc
  ${BORINGSSL_ROOT}src/crypto/trust_token/voprf.cc
  ${BORINGSSL_ROOT}src/crypto/x509/a_digest.cc
  ${BORINGSSL_ROOT}src/crypto/x509/a_sign.cc
  ${BORINGSSL_ROOT}src/crypto/x509/a_verify.cc
  ${BORINGSSL_ROOT}src/crypto/x509/algorithm.cc
  ${BORINGSSL_ROOT}src/crypto/x509/asn1_gen.cc
  ${BORINGSSL_ROOT}src/crypto/x509/by_dir.cc
  ${BORINGSSL_ROOT}src/crypto/x509/by_file.cc
  ${BORINGSSL_ROOT}src/crypto/x509/i2d_pr.cc
  ${BORINGSSL_ROOT}src/crypto/x509/name_print.cc
  ${BORINGSSL_ROOT}src/crypto/x509/policy.cc
  ${BORINGSSL_ROOT}src/crypto/x509/rsa_pss.cc
  ${BORINGSSL_ROOT}src/crypto/x509/t_crl.cc
  ${BORINGSSL_ROOT}src/crypto/x509/t_req.cc
  ${BORINGSSL_ROOT}src/crypto/x509/t_x509.cc
  ${BORINGSSL_ROOT}src/crypto/x509/t_x509a.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_akey.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_akeya.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_alt.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_bcons.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_bitst.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_conf.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_cpols.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_crld.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_enum.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_extku.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_genn.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_ia5.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_info.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_int.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_lib.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_ncons.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_ocsp.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_pcons.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_pmaps.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_prn.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_purp.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_skey.cc
  ${BORINGSSL_ROOT}src/crypto/x509/v3_utl.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_att.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_cmp.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_d2.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_def.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_ext.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_lu.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_obj.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_req.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_set.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_trs.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_txt.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_v3.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_vfy.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_vpm.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509cset.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509name.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509rset.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509spki.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_algor.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_all.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_attrib.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_crl.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_exten.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_name.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_pubkey.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_req.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_sig.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_spki.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_val.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_x509.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x_x509a.cc
  ${BORINGSSL_ROOT}src/crypto/xwing/xwing.cc
  ${BORINGSSL_ROOT}src/gen/crypto/err_data.cc
)
set(crypto_sources_asm
  ${BORINGSSL_ROOT}src/crypto/curve25519/asm/x25519-asm-arm.S
  ${BORINGSSL_ROOT}src/crypto/hrss/asm/poly_rq_mul.S
  ${BORINGSSL_ROOT}src/crypto/poly1305/poly1305_arm_asm.S
  ${BORINGSSL_ROOT}src/gen/bcm/aes-gcm-avx2-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/aes-gcm-avx2-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/aes-gcm-avx512-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/aes-gcm-avx512-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesni-gcm-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesni-gcm-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesni-x86-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesni-x86-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesni-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesni-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesv8-armv7-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesv8-armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesv8-armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesv8-armv8-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesv8-gcm-armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesv8-gcm-armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/aesv8-gcm-armv8-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/armv4-mont-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/armv8-mont-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/armv8-mont-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/armv8-mont-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/bn-586-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/bn-586-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/bn-armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/bn-armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/bn-armv8-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/bsaes-armv7-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/co-586-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/co-586-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-armv4-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-neon-armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-neon-armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-neon-armv8-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-ssse3-x86-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-ssse3-x86-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-ssse3-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-ssse3-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-x86-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-x86-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghashv8-armv7-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghashv8-armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghashv8-armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/ghashv8-armv8-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/p256-armv8-asm-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/p256-armv8-asm-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/p256-armv8-asm-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/p256-x86_64-asm-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/p256-x86_64-asm-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/p256_beeu-armv8-asm-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/p256_beeu-armv8-asm-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/p256_beeu-armv8-asm-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/p256_beeu-x86_64-asm-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/p256_beeu-x86_64-asm-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/rdrand-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/rdrand-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/rsaz-avx2-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/rsaz-avx2-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha1-586-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha1-586-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha1-armv4-large-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha1-armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha1-armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha1-armv8-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha1-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha1-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha256-586-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha256-586-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha256-armv4-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha256-armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha256-armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha256-armv8-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha256-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha256-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha512-586-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha512-586-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha512-armv4-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha512-armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha512-armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha512-armv8-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha512-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/sha512-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/vpaes-armv7-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/vpaes-armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/vpaes-armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/vpaes-armv8-win.S
  ${BORINGSSL_ROOT}src/gen/bcm/vpaes-x86-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/vpaes-x86-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/vpaes-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/vpaes-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/x86-mont-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/x86-mont-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/x86_64-mont-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/x86_64-mont-linux.S
  ${BORINGSSL_ROOT}src/gen/bcm/x86_64-mont5-apple.S
  ${BORINGSSL_ROOT}src/gen/bcm/x86_64-mont5-linux.S
  ${BORINGSSL_ROOT}src/gen/crypto/aes128gcmsiv-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/crypto/aes128gcmsiv-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha-armv4-linux.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha-armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha-armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha-armv8-win.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha-x86-apple.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha-x86-linux.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha20_poly1305_armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha20_poly1305_armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha20_poly1305_armv8-win.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha20_poly1305_x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/crypto/chacha20_poly1305_x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/crypto/md5-586-apple.S
  ${BORINGSSL_ROOT}src/gen/crypto/md5-586-linux.S
  ${BORINGSSL_ROOT}src/gen/crypto/md5-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/crypto/md5-x86_64-linux.S
  ${BORINGSSL_ROOT}src/gen/test_support/trampoline-armv4-linux.S
  ${BORINGSSL_ROOT}src/gen/test_support/trampoline-armv8-apple.S
  ${BORINGSSL_ROOT}src/gen/test_support/trampoline-armv8-linux.S
  ${BORINGSSL_ROOT}src/gen/test_support/trampoline-armv8-win.S
  ${BORINGSSL_ROOT}src/gen/test_support/trampoline-x86-apple.S
  ${BORINGSSL_ROOT}src/gen/test_support/trampoline-x86-linux.S
  ${BORINGSSL_ROOT}src/gen/test_support/trampoline-x86_64-apple.S
  ${BORINGSSL_ROOT}src/gen/test_support/trampoline-x86_64-linux.S
  ${BORINGSSL_ROOT}src/third_party/fiat/asm/fiat_curve25519_adx_mul.S
  ${BORINGSSL_ROOT}src/third_party/fiat/asm/fiat_curve25519_adx_square.S
  ${BORINGSSL_ROOT}src/third_party/fiat/asm/fiat_p256_adx_mul.S
  ${BORINGSSL_ROOT}src/third_party/fiat/asm/fiat_p256_adx_sqr.S
)
set(crypto_sources_nasm
  ${BORINGSSL_ROOT}src/gen/bcm/aes-gcm-avx2-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/aes-gcm-avx512-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/aesni-gcm-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/aesni-x86-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/aesni-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/bn-586-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/co-586-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-ssse3-x86-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-ssse3-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-x86-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/ghash-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/p256-x86_64-asm-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/p256_beeu-x86_64-asm-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/rdrand-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/rsaz-avx2-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/sha1-586-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/sha1-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/sha256-586-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/sha256-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/sha512-586-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/sha512-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/vpaes-x86-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/vpaes-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/x86-mont-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/x86_64-mont-win.asm
  ${BORINGSSL_ROOT}src/gen/bcm/x86_64-mont5-win.asm
  ${BORINGSSL_ROOT}src/gen/crypto/aes128gcmsiv-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/crypto/chacha-x86-win.asm
  ${BORINGSSL_ROOT}src/gen/crypto/chacha-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/crypto/chacha20_poly1305_x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/crypto/md5-586-win.asm
  ${BORINGSSL_ROOT}src/gen/crypto/md5-x86_64-win.asm
  ${BORINGSSL_ROOT}src/gen/test_support/trampoline-x86-win.asm
  ${BORINGSSL_ROOT}src/gen/test_support/trampoline-x86_64-win.asm
)
set(ssl_sources
  ${BORINGSSL_ROOT}src/ssl/bio_ssl.cc
  ${BORINGSSL_ROOT}src/ssl/d1_both.cc
  ${BORINGSSL_ROOT}src/ssl/d1_lib.cc
  ${BORINGSSL_ROOT}src/ssl/d1_pkt.cc
  ${BORINGSSL_ROOT}src/ssl/d1_srtp.cc
  ${BORINGSSL_ROOT}src/ssl/dtls_method.cc
  ${BORINGSSL_ROOT}src/ssl/dtls_record.cc
  ${BORINGSSL_ROOT}src/ssl/encrypted_client_hello.cc
  ${BORINGSSL_ROOT}src/ssl/extensions.cc
  ${BORINGSSL_ROOT}src/ssl/handoff.cc
  ${BORINGSSL_ROOT}src/ssl/handshake.cc
  ${BORINGSSL_ROOT}src/ssl/handshake_client.cc
  ${BORINGSSL_ROOT}src/ssl/handshake_server.cc
  ${BORINGSSL_ROOT}src/ssl/s3_both.cc
  ${BORINGSSL_ROOT}src/ssl/s3_lib.cc
  ${BORINGSSL_ROOT}src/ssl/s3_pkt.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_aead_ctx.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_asn1.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_buffer.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_cert.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_cipher.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_credential.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_file.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_key_share.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_lib.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_privkey.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_session.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_stat.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_transcript.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_versions.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_x509.cc
  ${BORINGSSL_ROOT}src/ssl/t1_enc.cc
  ${BORINGSSL_ROOT}src/ssl/tls13_both.cc
  ${BORINGSSL_ROOT}src/ssl/tls13_client.cc
  ${BORINGSSL_ROOT}src/ssl/tls13_enc.cc
  ${BORINGSSL_ROOT}src/ssl/tls13_server.cc
  ${BORINGSSL_ROOT}src/ssl/tls_method.cc
  ${BORINGSSL_ROOT}src/ssl/tls_record.cc
)
set(tool_sources
  ${BORINGSSL_ROOT}src/tool/args.cc
  ${BORINGSSL_ROOT}src/tool/ciphers.cc
  ${BORINGSSL_ROOT}src/tool/client.cc
  ${BORINGSSL_ROOT}src/tool/const.cc
  ${BORINGSSL_ROOT}src/tool/digest.cc
  ${BORINGSSL_ROOT}src/tool/fd.cc
  ${BORINGSSL_ROOT}src/tool/file.cc
  ${BORINGSSL_ROOT}src/tool/generate_ech.cc
  ${BORINGSSL_ROOT}src/tool/generate_ed25519.cc
  ${BORINGSSL_ROOT}src/tool/genrsa.cc
  ${BORINGSSL_ROOT}src/tool/pkcs12.cc
  ${BORINGSSL_ROOT}src/tool/rand.cc
  ${BORINGSSL_ROOT}src/tool/server.cc
  ${BORINGSSL_ROOT}src/tool/sign.cc
  ${BORINGSSL_ROOT}src/tool/speed.cc
  ${BORINGSSL_ROOT}src/tool/tool.cc
  ${BORINGSSL_ROOT}src/tool/transport_common.cc
)
set(test_support_sources
  ${BORINGSSL_ROOT}src/crypto/test/abi_test.cc
  ${BORINGSSL_ROOT}src/crypto/test/file_test.cc
  ${BORINGSSL_ROOT}src/crypto/test/file_test_gtest.cc
  ${BORINGSSL_ROOT}src/crypto/test/file_util.cc
  ${BORINGSSL_ROOT}src/crypto/test/test_data.cc
  ${BORINGSSL_ROOT}src/crypto/test/test_util.cc
  ${BORINGSSL_ROOT}src/crypto/test/wycheproof_util.cc
)
set(crypto_test_sources
  ${BORINGSSL_ROOT}src/crypto/abi_self_test.cc
  ${BORINGSSL_ROOT}src/crypto/asn1/asn1_test.cc
  ${BORINGSSL_ROOT}src/crypto/base64/base64_test.cc
  ${BORINGSSL_ROOT}src/crypto/bio/bio_test.cc
  ${BORINGSSL_ROOT}src/crypto/blake2/blake2_test.cc
  ${BORINGSSL_ROOT}src/crypto/buf/buf_test.cc
  ${BORINGSSL_ROOT}src/crypto/bytestring/bytestring_test.cc
  ${BORINGSSL_ROOT}src/crypto/chacha/chacha_test.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/aead_test.cc
  ${BORINGSSL_ROOT}src/crypto/cipher/cipher_test.cc
  ${BORINGSSL_ROOT}src/crypto/cms/cms_test.cc
  ${BORINGSSL_ROOT}src/crypto/compiler_test.cc
  ${BORINGSSL_ROOT}src/crypto/conf/conf_test.cc
  ${BORINGSSL_ROOT}src/crypto/constant_time_test.cc
  ${BORINGSSL_ROOT}src/crypto/cpu_arm_linux_test.cc
  ${BORINGSSL_ROOT}src/crypto/crypto_test.cc
  ${BORINGSSL_ROOT}src/crypto/curve25519/ed25519_test.cc
  ${BORINGSSL_ROOT}src/crypto/curve25519/spake25519_test.cc
  ${BORINGSSL_ROOT}src/crypto/curve25519/x25519_test.cc
  ${BORINGSSL_ROOT}src/crypto/dh/dh_test.cc
  ${BORINGSSL_ROOT}src/crypto/digest/digest_test.cc
  ${BORINGSSL_ROOT}src/crypto/dsa/dsa_test.cc
  ${BORINGSSL_ROOT}src/crypto/ecdh/ecdh_test.cc
  ${BORINGSSL_ROOT}src/crypto/ecdsa/ecdsa_p1363_test.cc
  ${BORINGSSL_ROOT}src/crypto/err/err_test.cc
  ${BORINGSSL_ROOT}src/crypto/evp/evp_extra_test.cc
  ${BORINGSSL_ROOT}src/crypto/evp/evp_test.cc
  ${BORINGSSL_ROOT}src/crypto/evp/pbkdf_test.cc
  ${BORINGSSL_ROOT}src/crypto/evp/scrypt_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/aes/aes_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/aes/gcm_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/bn_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/cmac/cmac_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/ec/ec_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/ec/p256-nistz_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/ec/p256_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/ecdsa/ecdsa_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/entropy/jitter_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/hkdf/hkdf_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/keccak/keccak_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/rand/ctrdrbg_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/service_indicator/service_indicator_test.cc
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/sha/sha_test.cc
  ${BORINGSSL_ROOT}src/crypto/hmac/hmac_test.cc
  ${BORINGSSL_ROOT}src/crypto/hpke/hpke_test.cc
  ${BORINGSSL_ROOT}src/crypto/hrss/hrss_test.cc
  ${BORINGSSL_ROOT}src/crypto/impl_dispatch_test.cc
  ${BORINGSSL_ROOT}src/crypto/kyber/kyber_test.cc
  ${BORINGSSL_ROOT}src/crypto/lhash/lhash_test.cc
  ${BORINGSSL_ROOT}src/crypto/md5/md5_test.cc
  ${BORINGSSL_ROOT}src/crypto/mem_test.cc
  ${BORINGSSL_ROOT}src/crypto/mldsa/mldsa_test.cc
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem_test.cc
  ${BORINGSSL_ROOT}src/crypto/obj/obj_test.cc
  ${BORINGSSL_ROOT}src/crypto/pem/pem_test.cc
  ${BORINGSSL_ROOT}src/crypto/pkcs7/pkcs7_test.cc
  ${BORINGSSL_ROOT}src/crypto/pkcs8/pkcs12_test.cc
  ${BORINGSSL_ROOT}src/crypto/pkcs8/pkcs8_test.cc
  ${BORINGSSL_ROOT}src/crypto/poly1305/poly1305_test.cc
  ${BORINGSSL_ROOT}src/crypto/pool/pool_test.cc
  ${BORINGSSL_ROOT}src/crypto/rand/fork_detect_test.cc
  ${BORINGSSL_ROOT}src/crypto/rand/getentropy_test.cc
  ${BORINGSSL_ROOT}src/crypto/rand/rand_test.cc
  ${BORINGSSL_ROOT}src/crypto/refcount_test.cc
  ${BORINGSSL_ROOT}src/crypto/rsa/rsa_test.cc
  ${BORINGSSL_ROOT}src/crypto/self_test.cc
  ${BORINGSSL_ROOT}src/crypto/siphash/siphash_test.cc
  ${BORINGSSL_ROOT}src/crypto/slhdsa/slhdsa_test.cc
  ${BORINGSSL_ROOT}src/crypto/spake2plus/spake2plus_test.cc
  ${BORINGSSL_ROOT}src/crypto/stack/stack_test.cc
  ${BORINGSSL_ROOT}src/crypto/test/gtest_main.cc
  ${BORINGSSL_ROOT}src/crypto/thread_test.cc
  ${BORINGSSL_ROOT}src/crypto/trust_token/trust_token_test.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_test.cc
  ${BORINGSSL_ROOT}src/crypto/x509/x509_time_test.cc
  ${BORINGSSL_ROOT}src/crypto/xwing/xwing_test.cc
  ${BORINGSSL_ROOT}src/third_party/fiat/bedrock_platform_test.cc
  ${BORINGSSL_ROOT}src/third_party/fiat/bedrock_polyfill_platform.c.inc
)
set(crypto_test_data
  ${BORINGSSL_ROOT}src/crypto/blake2/blake2b256_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_128_cbc_sha1_tls_implicit_iv_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_128_cbc_sha1_tls_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_128_ccm_bluetooth_8_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_128_ccm_bluetooth_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_128_ccm_matter_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_128_ctr_hmac_sha256.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_128_eax_test.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_128_gcm_randnonce_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_128_gcm_siv_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_128_gcm_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_192_gcm_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_256_cbc_sha1_tls_implicit_iv_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_256_cbc_sha1_tls_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_256_ctr_hmac_sha256.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_256_eax_test.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_256_gcm_randnonce_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_256_gcm_siv_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/aes_256_gcm_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/chacha20_poly1305_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/cipher_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/des_ede3_cbc_sha1_tls_implicit_iv_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/des_ede3_cbc_sha1_tls_tests.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/nist_cavp/aes_128_cbc.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/nist_cavp/aes_128_ctr.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/nist_cavp/aes_128_gcm.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/nist_cavp/aes_192_cbc.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/nist_cavp/aes_192_ctr.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/nist_cavp/aes_256_cbc.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/nist_cavp/aes_256_ctr.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/nist_cavp/aes_256_gcm.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/nist_cavp/tdes_cbc.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/nist_cavp/tdes_ecb.txt
  ${BORINGSSL_ROOT}src/crypto/cipher/test/xchacha20_poly1305_tests.txt
  ${BORINGSSL_ROOT}src/crypto/curve25519/ed25519_tests.txt
  ${BORINGSSL_ROOT}src/crypto/ecdh/ecdh_tests.txt
  ${BORINGSSL_ROOT}src/crypto/evp/test/dh_tests.txt
  ${BORINGSSL_ROOT}src/crypto/evp/test/ec_tests.txt
  ${BORINGSSL_ROOT}src/crypto/evp/test/ed25519_tests.txt
  ${BORINGSSL_ROOT}src/crypto/evp/test/evp_tests.txt
  ${BORINGSSL_ROOT}src/crypto/evp/test/rsa_tests.txt
  ${BORINGSSL_ROOT}src/crypto/evp/test/scrypt_tests.txt
  ${BORINGSSL_ROOT}src/crypto/evp/test/x25519_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/aes/aes_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/test/exp_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/test/gcd_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/test/miller_rabin_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/test/mod_exp_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/test/mod_inv_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/test/mod_mul_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/test/mod_sqrt_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/test/product_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/test/quotient_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/test/shift_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/bn/test/sum_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/cmac/cavp_3des_cmac_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/cmac/cavp_aes128_cmac_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/cmac/cavp_aes192_cmac_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/cmac/cavp_aes256_cmac_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/ec/ec_scalar_base_mult_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/ec/p256-nistz_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/ecdsa/ecdsa_sign_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/ecdsa/ecdsa_verify_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/keccak/keccak_tests.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/rand/ctrdrbg_df_vectors.txt
  ${BORINGSSL_ROOT}src/crypto/fipsmodule/rand/ctrdrbg_vectors.txt
  ${BORINGSSL_ROOT}src/crypto/hmac/hmac_tests.txt
  ${BORINGSSL_ROOT}src/crypto/hpke/hpke_test_vectors.txt
  ${BORINGSSL_ROOT}src/crypto/kyber/kyber_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mldsa/mldsa_nist_keygen_44_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mldsa/mldsa_nist_keygen_65_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mldsa/mldsa_nist_keygen_87_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mldsa/mldsa_nist_siggen_44_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mldsa/mldsa_nist_siggen_65_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mldsa/mldsa_nist_siggen_87_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem1024_decap_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem1024_encap_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem1024_keygen_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem1024_nist_decap_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem1024_nist_keygen_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem768_decap_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem768_encap_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem768_keygen_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem768_nist_decap_tests.txt
  ${BORINGSSL_ROOT}src/crypto/mlkem/mlkem768_nist_keygen_tests.txt
  ${BORINGSSL_ROOT}src/crypto/pkcs7/test/nss.p7c
  ${BORINGSSL_ROOT}src/crypto/pkcs7/test/openssl_crl.p7c
  ${BORINGSSL_ROOT}src/crypto/pkcs7/test/sign_cert.pem
  ${BORINGSSL_ROOT}src/crypto/pkcs7/test/sign_key.pem
  ${BORINGSSL_ROOT}src/crypto/pkcs7/test/sign_sha1.p7s
  ${BORINGSSL_ROOT}src/crypto/pkcs7/test/sign_sha1_key_id.p7s
  ${BORINGSSL_ROOT}src/crypto/pkcs7/test/sign_sha256.p7s
  ${BORINGSSL_ROOT}src/crypto/pkcs7/test/sign_sha256_key_id.p7s
  ${BORINGSSL_ROOT}src/crypto/pkcs7/test/windows.p7c
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/bad1.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/bad2.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/bad3.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/empty_password.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/empty_password_ber.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/empty_password_ber_nested.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/no_encryption.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/nss.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/null_password.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/openssl.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/pbes2_sha1.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/pbes2_sha256.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/unicode_password.p12
  ${BORINGSSL_ROOT}src/crypto/pkcs8/test/windows.p12
  ${BORINGSSL_ROOT}src/crypto/poly1305/poly1305_tests.txt
  ${BORINGSSL_ROOT}src/crypto/rsa/test/rsa511.pem
  ${BORINGSSL_ROOT}src/crypto/rsa/test/rsa511pub.pem
  ${BORINGSSL_ROOT}src/crypto/rsa/test/rsa512.pem
  ${BORINGSSL_ROOT}src/crypto/rsa/test/rsa512pub.pem
  ${BORINGSSL_ROOT}src/crypto/rsa/test/rsa8192.pem
  ${BORINGSSL_ROOT}src/crypto/rsa/test/rsa8192pub.pem
  ${BORINGSSL_ROOT}src/crypto/rsa/test/rsa8193.pem
  ${BORINGSSL_ROOT}src/crypto/rsa/test/rsa8193pub.pem
  ${BORINGSSL_ROOT}src/crypto/siphash/siphash_tests.txt
  ${BORINGSSL_ROOT}src/crypto/slhdsa/slhdsa_keygen.txt
  ${BORINGSSL_ROOT}src/crypto/slhdsa/slhdsa_prehash.txt
  ${BORINGSSL_ROOT}src/crypto/slhdsa/slhdsa_siggen.txt
  ${BORINGSSL_ROOT}src/crypto/slhdsa/slhdsa_sigver.txt
  ${BORINGSSL_ROOT}src/crypto/x509/test/basic_constraints_ca.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/basic_constraints_ca_pathlen_0.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/basic_constraints_ca_pathlen_1.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/basic_constraints_ca_pathlen_10.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/basic_constraints_leaf.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/basic_constraints_none.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_intermediate.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_intermediate_authority_key_identifier.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_intermediate_basic_constraints.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_intermediate_ext_key_usage.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_intermediate_key_usage.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_intermediate_name_constraints.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_intermediate_subject_alt_name.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_intermediate_subject_key_identifier.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_leaf.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_leaf_authority_key_identifier.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_leaf_basic_constraints.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_leaf_ext_key_usage.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_leaf_key_usage.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_leaf_name_constraints.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_leaf_subject_alt_name.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_leaf_subject_key_identifier.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_root.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_root_authority_key_identifier.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_root_basic_constraints.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_root_ext_key_usage.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_root_key_usage.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_root_name_constraints.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_root_subject_alt_name.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/invalid_extension_root_subject_key_identifier.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/many_constraints.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/many_names1.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/many_names2.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/many_names3.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate_any.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate_duplicate.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate_invalid.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate_mapped.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate_mapped_any.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate_mapped_oid3.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate_require.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate_require1.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate_require2.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate_require_duplicate.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_intermediate_require_no_policies.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf_any.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf_duplicate.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf_invalid.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf_none.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf_oid1.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf_oid2.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf_oid3.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf_oid4.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf_oid5.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf_require.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_leaf_require1.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_root.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_root2.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/policy_root_cross_inhibit_mapping.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha1.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha1_explicit.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha1_mgf1_syntax_error.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha224.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha256.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha256_explicit_trailer.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha256_mgf1_sha384.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha256_mgf1_syntax_error.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha256_omit_nulls.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha256_salt31.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha256_salt_overflow.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha256_unknown_mgf.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha256_wrong_trailer.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha384.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/pss_sha512.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/some_names1.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/some_names2.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/some_names3.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/trailing_data_leaf_authority_key_identifier.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/trailing_data_leaf_basic_constraints.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/trailing_data_leaf_ext_key_usage.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/trailing_data_leaf_key_usage.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/trailing_data_leaf_name_constraints.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/trailing_data_leaf_subject_alt_name.pem
  ${BORINGSSL_ROOT}src/crypto/x509/test/trailing_data_leaf_subject_key_identifier.pem
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/aes_cbc_pkcs5_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/aes_cmac_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/aes_eax_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/aes_gcm_siv_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/aes_gcm_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/chacha20_poly1305_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/dsa_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdh_secp224r1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdh_secp256r1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdh_secp384r1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdh_secp521r1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp224r1_sha224_p1363_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp224r1_sha224_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp224r1_sha256_p1363_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp224r1_sha256_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp224r1_sha512_p1363_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp224r1_sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp256r1_sha256_p1363_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp256r1_sha256_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp256r1_sha512_p1363_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp256r1_sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp384r1_sha384_p1363_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp384r1_sha384_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp384r1_sha512_p1363_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp384r1_sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp521r1_sha512_p1363_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/ecdsa_secp521r1_sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/eddsa_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/hkdf_sha1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/hkdf_sha256_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/hkdf_sha384_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/hkdf_sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/hmac_sha1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/hmac_sha224_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/hmac_sha256_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/hmac_sha384_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/hmac_sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/kw_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/kwp_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/mldsa_44_standard_sign_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/mldsa_44_standard_verify_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/mldsa_65_standard_sign_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/mldsa_65_standard_verify_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/mldsa_87_standard_sign_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/mldsa_87_standard_verify_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/primality_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_2048_sha1_mgf1sha1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_2048_sha224_mgf1sha1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_2048_sha224_mgf1sha224_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_2048_sha256_mgf1sha1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_2048_sha256_mgf1sha256_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_2048_sha384_mgf1sha1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_2048_sha384_mgf1sha384_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_2048_sha512_mgf1sha1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_2048_sha512_mgf1sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_3072_sha256_mgf1sha1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_3072_sha256_mgf1sha256_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_3072_sha512_mgf1sha1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_3072_sha512_mgf1sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_4096_sha256_mgf1sha1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_4096_sha256_mgf1sha256_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_4096_sha512_mgf1sha1_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_4096_sha512_mgf1sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_oaep_misc_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_pkcs1_2048_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_pkcs1_3072_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_pkcs1_4096_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_pss_2048_sha1_mgf1_20_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_pss_2048_sha256_mgf1_0_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_pss_2048_sha256_mgf1_32_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_pss_3072_sha256_mgf1_32_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_pss_4096_sha256_mgf1_32_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_pss_4096_sha512_mgf1_32_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_pss_misc_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_sig_gen_misc_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_signature_2048_sha224_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_signature_2048_sha256_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_signature_2048_sha384_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_signature_2048_sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_signature_3072_sha256_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_signature_3072_sha384_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_signature_3072_sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_signature_4096_sha384_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_signature_4096_sha512_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/rsa_signature_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/x25519_test.txt
  ${BORINGSSL_ROOT}src/third_party/wycheproof_testvectors/xchacha20_poly1305_test.txt
)
set(ssl_test_sources
  ${BORINGSSL_ROOT}src/crypto/test/gtest_main.cc
  ${BORINGSSL_ROOT}src/ssl/span_test.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_c_test.c
  ${BORINGSSL_ROOT}src/ssl/ssl_internal_test.cc
  ${BORINGSSL_ROOT}src/ssl/ssl_test.cc
)
